//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShapeFiles {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShapeFiles.ShapeFiles.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Cities_Towns {
            get {
                object obj = ResourceManager.GetObject("USA_Cities_Towns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--&lt;!DOCTYPE metadata SYSTEM &quot;http://www.esri.com/metadata/esriprof80.dtd&quot;&gt;--&gt;
        ///&lt;metadata xml:lang=&quot;es&quot;&gt;&lt;Esri&gt;&lt;CreaDate&gt;20150108&lt;/CreaDate&gt;&lt;CreaTime&gt;21061000&lt;/CreaTime&gt;&lt;SyncOnce&gt;TRUE&lt;/SyncOnce&gt;&lt;DataProperties&gt;&lt;lineage&gt;&lt;Process ToolSource=&quot;C:\Program Files (x86)\ArcGIS\ArcToolbox\Toolboxes\Data Management Tools.tbx\DefineProjection&quot; Date=&quot;20150107&quot; Time=&quot;162057&quot;&gt;DefineProjection USA_Places GEOGCS[&apos;GCS_WGS_1984&apos;,DATUM[&apos;D_WGS_1984&apos;,SPHEROID[&apos;WGS_1984&apos;,6378137.0,298.257223563]],PRIMEM[&apos;G [rest of string was truncated]&quot;;.
        /// </summary>
        public static string USA_Cities_Towns_shp {
            get {
                return ResourceManager.GetString("USA_Cities_Towns_shp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Cities_Towns1 {
            get {
                object obj = ResourceManager.GetObject("USA_Cities_Towns1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Cities_Towns2 {
            get {
                object obj = ResourceManager.GetObject("USA_Cities_Towns2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Cities_Towns3 {
            get {
                object obj = ResourceManager.GetObject("USA_Cities_Towns3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Cities_Towns4 {
            get {
                object obj = ResourceManager.GetObject("USA_Cities_Towns4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Cities_Towns5 {
            get {
                object obj = ResourceManager.GetObject("USA_Cities_Towns5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Counties {
            get {
                object obj = ResourceManager.GetObject("USA_Counties", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--&lt;!DOCTYPE metadata SYSTEM &quot;http://www.esri.com/metadata/esriprof80.dtd&quot;&gt;--&gt;
        ///&lt;metadata xml:lang=&quot;es&quot;&gt;&lt;Esri&gt;&lt;MetaID&gt;{1F5B4A54-0C42-4D89-B93D-6EDB8853D337}&lt;/MetaID&gt;&lt;CreaDate&gt;20150107&lt;/CreaDate&gt;&lt;CreaTime&gt;16120900&lt;/CreaTime&gt;&lt;SyncOnce&gt;TRUE&lt;/SyncOnce&gt;&lt;DataProperties&gt;&lt;lineage&gt;&lt;Process ToolSource=&quot;C:\Program Files (x86)\ArcGIS\ArcToolbox\Toolboxes\Data Management Tools.tbx\DefineProjection&quot; Date=&quot;20150107&quot; Time=&quot;161209&quot;&gt;DefineProjection USA_Counties GEOGCS[&apos;GCS_WGS_1984&apos;,DATUM[&apos;D_WGS_1984 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string USA_Counties_shp {
            get {
                return ResourceManager.GetString("USA_Counties_shp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Counties1 {
            get {
                object obj = ResourceManager.GetObject("USA_Counties1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Counties2 {
            get {
                object obj = ResourceManager.GetObject("USA_Counties2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Counties3 {
            get {
                object obj = ResourceManager.GetObject("USA_Counties3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Counties4 {
            get {
                object obj = ResourceManager.GetObject("USA_Counties4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Counties5 {
            get {
                object obj = ResourceManager.GetObject("USA_Counties5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Roads {
            get {
                object obj = ResourceManager.GetObject("USA_Roads", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--&lt;!DOCTYPE metadata SYSTEM &quot;http://www.esri.com/metadata/esriprof80.dtd&quot;&gt;--&gt;
        ///&lt;metadata xml:lang=&quot;es&quot;&gt;&lt;Esri&gt;&lt;MetaID&gt;{883D0305-41AF-4B47-ACF1-F9659375C111}&lt;/MetaID&gt;&lt;CreaDate&gt;20150107&lt;/CreaDate&gt;&lt;CreaTime&gt;16213600&lt;/CreaTime&gt;&lt;SyncOnce&gt;TRUE&lt;/SyncOnce&gt;&lt;DataProperties&gt;&lt;lineage&gt;&lt;Process ToolSource=&quot;C:\Program Files (x86)\ArcGIS\ArcToolbox\Toolboxes\Data Management Tools.tbx\DefineProjection&quot; Date=&quot;20150107&quot; Time=&quot;162136&quot;&gt;DefineProjection USA_Roads GEOGCS[&apos;GCS_WGS_1984&apos;,DATUM[&apos;D_WGS_1984&apos;,S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string USA_Roads_shp {
            get {
                return ResourceManager.GetString("USA_Roads_shp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Roads1 {
            get {
                object obj = ResourceManager.GetObject("USA_Roads1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Roads2 {
            get {
                object obj = ResourceManager.GetObject("USA_Roads2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Roads3 {
            get {
                object obj = ResourceManager.GetObject("USA_Roads3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Roads4 {
            get {
                object obj = ResourceManager.GetObject("USA_Roads4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_Roads5 {
            get {
                object obj = ResourceManager.GetObject("USA_Roads5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_States {
            get {
                object obj = ResourceManager.GetObject("USA_States", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--&lt;!DOCTYPE metadata SYSTEM &quot;http://www.esri.com/metadata/esriprof80.dtd&quot;&gt;--&gt;
        ///&lt;metadata xml:lang=&quot;es&quot;&gt;&lt;Esri&gt;&lt;MetaID&gt;{35EC4BB3-AB33-4678-BD54-F7BCA4EC949C}&lt;/MetaID&gt;&lt;CreaDate&gt;20150107&lt;/CreaDate&gt;&lt;CreaTime&gt;16215200&lt;/CreaTime&gt;&lt;SyncOnce&gt;TRUE&lt;/SyncOnce&gt;&lt;DataProperties&gt;&lt;lineage&gt;&lt;Process ToolSource=&quot;C:\Program Files (x86)\ArcGIS\ArcToolbox\Toolboxes\Data Management Tools.tbx\DefineProjection&quot; Date=&quot;20150107&quot; Time=&quot;162152&quot;&gt;DefineProjection USA_States GEOGCS[&apos;GCS_WGS_1984&apos;,DATUM[&apos;D_WGS_1984&apos;, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string USA_States_shp {
            get {
                return ResourceManager.GetString("USA_States_shp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_States1 {
            get {
                object obj = ResourceManager.GetObject("USA_States1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_States2 {
            get {
                object obj = ResourceManager.GetObject("USA_States2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_States3 {
            get {
                object obj = ResourceManager.GetObject("USA_States3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_States4 {
            get {
                object obj = ResourceManager.GetObject("USA_States4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] USA_States5 {
            get {
                object obj = ResourceManager.GetObject("USA_States5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Cities {
            get {
                object obj = ResourceManager.GetObject("World_Cities", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--&lt;!DOCTYPE metadata SYSTEM &quot;http://www.esri.com/metadata/esriprof80.dtd&quot;&gt;--&gt;
        ///&lt;metadata xml:lang=&quot;es&quot;&gt;&lt;Esri&gt;&lt;MetaID&gt;{2C500011-2F12-41E1-BFFE-61DC4C462661}&lt;/MetaID&gt;&lt;CreaDate&gt;20141229&lt;/CreaDate&gt;&lt;CreaTime&gt;15564400&lt;/CreaTime&gt;&lt;SyncOnce&gt;TRUE&lt;/SyncOnce&gt;&lt;DataProperties&gt;&lt;lineage&gt;&lt;Process ToolSource=&quot;C:\Program Files (x86)\ArcGIS\ArcToolbox\Toolboxes\Data Management Tools.tbx\DefineProjection&quot; Date=&quot;20141229&quot; Time=&quot;155644&quot;&gt;DefineProjection World_Cities GEOGCS[&apos;GCS_WGS_1984&apos;,DATUM[&apos;D_WGS_1984 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string World_Cities_shp {
            get {
                return ResourceManager.GetString("World_Cities_shp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Cities1 {
            get {
                object obj = ResourceManager.GetObject("World_Cities1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Cities2 {
            get {
                object obj = ResourceManager.GetObject("World_Cities2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Cities3 {
            get {
                object obj = ResourceManager.GetObject("World_Cities3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Cities4 {
            get {
                object obj = ResourceManager.GetObject("World_Cities4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Cities5 {
            get {
                object obj = ResourceManager.GetObject("World_Cities5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Countries {
            get {
                object obj = ResourceManager.GetObject("World_Countries", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;metadata xml:lang=&quot;es&quot;&gt;&lt;Esri&gt;&lt;CreaDate&gt;20140718&lt;/CreaDate&gt;&lt;CreaTime&gt;10045300&lt;/CreaTime&gt;&lt;ArcGISFormat&gt;1.0&lt;/ArcGISFormat&gt;&lt;SyncOnce&gt;TRUE&lt;/SyncOnce&gt;&lt;DataProperties&gt;&lt;lineage&gt;&lt;Process ToolSource=&quot;C:\Program Files (x86)\ArcGIS\Desktop10.0\ArcToolbox\Toolboxes\Data Management Tools.tbx\DefineProjection&quot; Date=&quot;20140718&quot; Time=&quot;100453&quot;&gt;DefineProjection World_Countries GEOGCS[&apos;GCS_WGS_1984&apos;,DATUM[&apos;D_WGS_1984&apos;,SPHEROID[&apos;WGS_1984&apos;,6378137.0,298.257223563]],PRIMEM[&apos;Greenwich&apos;,0.0], [rest of string was truncated]&quot;;.
        /// </summary>
        public static string World_Countries_shp {
            get {
                return ResourceManager.GetString("World_Countries_shp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Countries1 {
            get {
                object obj = ResourceManager.GetObject("World_Countries1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Countries2 {
            get {
                object obj = ResourceManager.GetObject("World_Countries2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Countries3 {
            get {
                object obj = ResourceManager.GetObject("World_Countries3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Countries4 {
            get {
                object obj = ResourceManager.GetObject("World_Countries4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Countries5 {
            get {
                object obj = ResourceManager.GetObject("World_Countries5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Hydrography {
            get {
                object obj = ResourceManager.GetObject("World_Hydrography", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Hydrography1 {
            get {
                object obj = ResourceManager.GetObject("World_Hydrography1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Hydrography2 {
            get {
                object obj = ResourceManager.GetObject("World_Hydrography2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Hydrography3 {
            get {
                object obj = ResourceManager.GetObject("World_Hydrography3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Hydrography4 {
            get {
                object obj = ResourceManager.GetObject("World_Hydrography4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Hydrography5 {
            get {
                object obj = ResourceManager.GetObject("World_Hydrography5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Lakes {
            get {
                object obj = ResourceManager.GetObject("World_Lakes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Lakes1 {
            get {
                object obj = ResourceManager.GetObject("World_Lakes1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Lakes2 {
            get {
                object obj = ResourceManager.GetObject("World_Lakes2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Lakes3 {
            get {
                object obj = ResourceManager.GetObject("World_Lakes3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Lakes4 {
            get {
                object obj = ResourceManager.GetObject("World_Lakes4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] World_Lakes5 {
            get {
                object obj = ResourceManager.GetObject("World_Lakes5", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
